// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.en');

goog.require('Blockly.Msg');

Blockly.Msg.ERROR_BETA_WARNING = "YOUR ARE USING A PRE-RELEASE VERSION! PLEASE USE A STABLE RELEASE INSTEAD!";
Blockly.Msg.IR_REMOTE_BUTTON_A = "A";
Blockly.Msg.IR_REMOTE_BUTTON_B = "B";
Blockly.Msg.IR_REMOTE_BUTTON_BUTTON = " button";
Blockly.Msg.IR_REMOTE_BUTTON_C = "C";
Blockly.Msg.IR_REMOTE_BUTTON_DOWN = "Down";
Blockly.Msg.IR_REMOTE_BUTTON_HELPURL = "http://z3t0.github.io/Arduino-IRremote/";
Blockly.Msg.IR_REMOTE_BUTTON_LEFT = "Left";
Blockly.Msg.IR_REMOTE_BUTTON_POWER = "Power";
Blockly.Msg.IR_REMOTE_BUTTON_RIGHT = "Right";
Blockly.Msg.IR_REMOTE_BUTTON_SELECT = "Select";
Blockly.Msg.IR_REMOTE_BUTTON_UP = "Up";
Blockly.Msg.IR_REMOTE_TOOLTIP_BUTTON_DOWN = "The down arrow on the remote.";
Blockly.Msg.IR_REMOTE_TOOLTIP_BUTTON_LEFT = "The left arrow on the remote.";
Blockly.Msg.IR_REMOTE_TOOLTIP_BUTTON_RIGHT = "The right arrow on the remote.";
Blockly.Msg.IR_REMOTE_TOOLTIP_BUTTON_SELECT = "The select button on the remote (the circle in the middle of the arrows).";
Blockly.Msg.IR_REMOTE_TOOLTIP_BUTTON_UP = "The up arrow on the remote.";
Blockly.Msg.IR_REMOTE_TOOLTIP_GET = "Poll for a new button input on the given pin.";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.VARIABLES_SET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.VARIABLES_GET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;